baseURL = 'https://streamlining-devex.netlify.app/'
languageCode = 'en-us'
title = 'Streamlining DevEx: The Power of CI/CD Standardization and Interoperability'
theme = ["github.com/dzello/reveal-hugo"]

[outputFormats.Reveal]
  baseName = "index"
  mediaType = "text/html"
  isHTML = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  # [markup.highlight]
  #   codeFences = true
  #   style = "monokai"

[params]
  [params.logo]
    src = '/images/twitter-iamjerdog.png'
    top = '90%'
    left = '80%'
    width = '15%'
  [params.logo-btm-left]
    src = '/images/placeholder.jpeg'  # autogen from https://picsum.photos/
    top = '90%'
    left = '5%'
    width = '15%'
    #opacity = '0.5'
  [params.appearance]
    font = 'Open Sans'
    font_size = 5

[params.reveal_hugo]
    theme = 'night'
    margin = 0.1
    transition = 'slide'
    transitionSpeed = 'fast'
    slideNumber = false
    controls = false
    hash = true
    respondToHashChanges = true
    jumpToSlide = true
    keyboard = true
    overview = true
    fragments = true
    fragmentInURL = true
    pause = true
    progress = true
    history = false
    center = true
    loop = false
    help = true
    mouseWheel = false
    hideAddressBar = true
    previewLinks = false
    custom_css = false
    disable_layout = false
    display = 'block'
    load_default_plugins = true
    