baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Streamlining DevEx: The Power of CI/CD Standardization and Interoperability'
theme = ["github.com/dzello/reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true